import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title> Portfolio Classic Theme </title>
        <meta  name="description" content="Generated by vnsoff"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
    </div>
  );
}
